---
# Source: feed/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: feed
    app.kubernetes.io/instance: feed
    app.kubernetes.io/version: "sha-c6ce27c28256dbb6fc77de73733bb019a3a2f379"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: feed
      app.kubernetes.io/instance: feed
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: feed
        app.kubernetes.io/instance: feed
      annotations:
        checksum/config: f4d9dbb3dac47d87735dc42312a836482aa3d286093fa3a22262bb72fe18d4e3
    spec:
      imagePullSecrets: 
        - name: ghcr-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: feed
          image: "ghcr.io/trip-manager-htwg/backend/feed:sha-c6ce27c28256dbb6fc77de73733bb019a3a2f379"
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8089"
            - name: AUTH_SERVICE_URL
              value: http://auth.trip-manager-prod.svc.cluster.local:8082
            - name: CORS_ALLOWED_ORIGINS
              value: https://neatnode.xyz,https://www.neatnode.xyz
            - name: OTEL_COLLECTOR_ENDPOINT
              value: otel-collector.trip-manager-prod.svc.cluster.local:4317
            - name: GCP_PROJECT_ID
              value: ornate-reef-501614-a1
            - name: PUBSUB_SUBSCRIPTION_ID
              value: trip-events-sub
          envFrom: 
            - secretRef:
                name: feed-secrets
          resources: 
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: feed
