---
# Source: cluster-config/templates/clustersecretstore.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: project-32c60644-299b-4b05-8cf
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: trip-manager-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
