---
# Source: cluster-config/templates/ghcr-pull-secrets.yaml
# helm/cluster-config/templates/ghcr-pull-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
    template:
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"auth":"e3sgLnRva2VuIH19"}}}
  data:
    - secretKey: token
      remoteKey: github-pat-packages
