---
# Source: newsletter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newsletter
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: newsletter
    app.kubernetes.io/instance: newsletter
    app.kubernetes.io/version: "sha-1130fd8f5c20fea3840629f087d25c79f4352d1c"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: newsletter-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
