---
# Source: newsletter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newsletter
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: newsletter
    app.kubernetes.io/instance: newsletter
    app.kubernetes.io/version: "sha-a0519ce51dd53783fc96f441210d9691f75ca530"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: newsletter-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
