---
# Source: otel-collector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: trip-manager-prod
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_mib: 200

    exporters:
      googlecloud:
        project: project-32c60644-299b-4b05-8cf
        metric:
          prefix: "custom.googleapis.com/trip_manager"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters:
            - googlecloud
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters:
            - googlecloud
