---
# Source: otel-collector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: trip-manager-prod
  annotations:
    iam.gke.io/gcp-service-account: "otel-collector-sa@project-32c60644-299b-4b05-8cf.iam.gserviceaccount.com"
