---
# Source: frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "sha-1130fd8f5c20fea3840629f087d25c79f4352d1c"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
