---
# Source: frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "sha-2658f85fdd68ff698c67ba3b03d1bce2a693b853"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
