---
# Source: frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "sha-abd4733ab95c1d50b6fd637aba11279b5c72914c"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
