---
# Source: travel-info/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-info
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: travel-info
    app.kubernetes.io/instance: travel-info
    app.kubernetes.io/version: "sha-e9516e25932bb6fc794f072a017d5d80122f199b"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: travel-info
      app.kubernetes.io/instance: travel-info
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: travel-info
        app.kubernetes.io/instance: travel-info
      annotations:
        checksum/config: 55b3a70ee53218c140703118564892564dd4a5cf426ad1e0e1b04d49e2964cc7
    spec:
      imagePullSecrets: 
        - name: '[map[name:ghcr-secret]]'
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: travel-info
          image: "ghcr.io/trip-manager-htwg/backend/travel-info:sha-e9516e25932bb6fc794f072a017d5d80122f199b"
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8087"
            - name: LOG_LEVEL
              value: info
            - name: AUTH_SERVICE_URL
              value: http://auth.trip-manager-prod.svc.cluster.local:8082
            - name: TRAVEL_API_URL
              value: https://www.auswaertiges-amt.de/opendata/travelwarning
            - name: WEATHER_API_URL
              value: https://api.open-meteo.com/v1/forecast
            - name: FORECAST_DAYS
              value: "3"
            - name: CACHE_TTL_HOURS
              value: "25"
            - name: CORS_ALLOWED_ORIGINS
              value: https://neatnode.xyz,https://www.neatnode.xyz
            - name: OTEL_COLLECTOR_ENDPOINT
              value: otel-collector.trip-manager-prod.svc.cluster.local:4317
          envFrom: 
            - secretRef:
                name: travel-info-secrets
          resources: 
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: travel-info
