---
# Source: travel-info/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: travel-info
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: travel-info
    app.kubernetes.io/instance: travel-info
    app.kubernetes.io/version: "sha-e9516e25932bb6fc794f072a017d5d80122f199b"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: travel-info
    app.kubernetes.io/instance: travel-info
---
# Source: travel-info/templates/service.yaml
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: travel-info-hc-policy
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: travel-info
    app.kubernetes.io/instance: travel-info
    app.kubernetes.io/version: "sha-e9516e25932bb6fc794f072a017d5d80122f199b"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8087
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: travel-info
