---
# Source: trips/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trips
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: trips
    app.kubernetes.io/instance: trips
    app.kubernetes.io/version: "sha-4834615eb48f16c42bda633a617a899871403fbc"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: trips-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
