---
# Source: social/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: social
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: social
    app.kubernetes.io/instance: social
    app.kubernetes.io/version: "sha-d90b2a6ad17c714fd268254b309ba6318e4a6a1d"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: social-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
