---
# Source: social/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: social
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: social
    app.kubernetes.io/instance: social
    app.kubernetes.io/version: "sha-e9516e25932bb6fc794f072a017d5d80122f199b"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: social-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
