---
# Source: users/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/version: "sha-2e10460dc13fe8ccfe27a8fba50dc166b8d69e0a"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users
      app.kubernetes.io/instance: users
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: users
        app.kubernetes.io/instance: users
      annotations:
        checksum/config: c569e9737a0ac56353bc4f2e8a9201ffee0f59725d433d5698523cc2358e2c0e
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: users
          image: "europe-west1-docker.pkg.dev/project-32c60644-299b-4b05-8cf/trip-manager/backend/users:sha-2e10460dc13fe8ccfe27a8fba50dc166b8d69e0a"
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
          env: 
            - name: PORT
              value: "8083"
            - name: LOG_LEVEL
              value: info
            - name: AUTH_SERVICE_URL
              value: http://auth.trip-manager-prod.svc.cluster.local:8082
            - name: STORAGE_BUCKET_URL
              value: https://storage.googleapis.com/trip-manager-bucket
            - name: CORS_ALLOWED_ORIGINS
              value: https://neatnode.xyz,https://www.neatnode.xyz
            - name: OTEL_COLLECTOR_ENDPOINT
              value: otel-collector.trip-manager-prod.svc.cluster.local:4317
            - name: GCP_PROJECT_ID
              value: project-32c60644-299b-4b05-8cf
            - name: GITHUB_REPO
              value: ShalArl/trip-manager
            - name: GITHUB_BRANCH
              value: gitops-prod
            - name: BASE_URL
              value: https://www.neatnode.xyz
          envFrom: 
            - secretRef:
                name: users-secrets
          resources: 
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      serviceAccountName: users
