---
# Source: users/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/version: "sha-c6ce27c28256dbb6fc77de73733bb019a3a2f379"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
---
# Source: users/templates/service.yaml
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: users-hc-policy
  namespace: trip-manager-prod
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/version: "sha-c6ce27c28256dbb6fc77de73733bb019a3a2f379"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8083
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: users
