---
# Source: users/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: users
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: users
    app.kubernetes.io/version: "sha-2658f85fdd68ff698c67ba3b03d1bce2a693b853"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: users-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
