---
# Source: auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: trip-manager-prod
  labels: 
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: auth
    app.kubernetes.io/version: "sha-675b2d494a7486fd48d57c9a0876996645fb1262"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: trip-manager
  annotations:
    iam.gke.io/gcp-service-account: auth-sa@ornate-reef-501614-a1.iam.gserviceaccount.com
