---
# Source: users-postgres/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-postgres-config
  namespace: trip-manager-prod
data:
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host    all             all             all                     md5
