---
# Source: users-postgres/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-postgres-secret
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: users-postgres-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: users-database-password
