---
# Source: redis/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-password
