---
# Source: neo4j/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-secret
  namespace: trip-manager-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: neo4j-secret
  data:
    - secretKey: NEO4J_PASSWORD
      remoteRef:
        key: neo4j-password
