---
# Source: neo4j/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: trip-manager-prod
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:5.19-community
          ports:
            - containerPort: 7687
            - containerPort: 7474
          env:
            - name: _NEO4J_PASS
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_PASSWORD
            - name: NEO4J_AUTH
              value: "neo4j/$(_NEO4J_PASS)"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "apoc.*"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 8Gi
